## NEWS
GET http://localhost:5000/api/news?page=2&perPage=5
Content-Type: application/json

# GET http://localhost:5000/api/news/full
# GET http://localhost:5000/api/news/61c5d5d37ba9e510422c1aa0

## USERS
# GET http://localhost:5000/api/users
